    - name: Build API gateway image
      run: |
        docker build -t ghcr.io/melgholabzouri/api-gateway:latest api-gateway
        docker push ghcr.io/melgholabzouri/api-gateway:latest

    - name: Build backend image
      run: |
        docker build -t ghcr.io/melgholabzouri/backend:latest backend
        docker push ghcr.io/melgholabzouri/backend:latest
